import type { Job } from "./types";

const MS_HOUR = 3_600_000;

/** Relative-to-now timestamps keep the "posted X ago" column feeling live. */
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * MS_HOUR).toISOString();
}

export const JOBS: Job[] = [
  {
    id: "amzn-sde-2027",
    companyName: "Amazon",
    roleTitle: "Software Development Engineer Intern",
    season: "Summer 2027",
    location: "Seattle, WA",
    workType: "On-Site",
    compensation: "$10,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(1),
    applicationUrl: "https://amazon.jobs",
    category: "SWE",
  },
  {
    id: "aapl-ai-2027",
    companyName: "Apple",
    roleTitle: "Machine Learning Intern — Siri AI",
    season: "Summer 2027",
    location: "Cupertino, CA",
    workType: "On-Site",
    compensation: "$50 - $65/hr",
    sponsorship: "Yes",
    datePosted: hoursAgo(2),
    applicationUrl: "https://jobs.apple.com",
    category: "AI/ML",
  },
  {
    id: "tsla-embedded-2027",
    companyName: "Tesla",
    roleTitle: "Embedded Software Engineer Intern, Firmware",
    season: "Summer 2027",
    location: "Palo Alto, CA",
    workType: "On-Site",
    compensation: "$9,500/mo",
    sponsorship: "No",
    datePosted: hoursAgo(3),
    applicationUrl: "https://www.tesla.com/careers",
    category: "Systems/Infrastructure",
  },
  {
    id: "pltr-fde-2027",
    companyName: "Palantir",
    roleTitle: "Forward Deployed Software Engineer Intern",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "Hybrid",
    compensation: "$12,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(5),
    applicationUrl: "https://www.palantir.com/careers",
    category: "SWE",
  },
  {
    id: "notion-sw-2027",
    companyName: "Notion",
    roleTitle: "Software Engineer Intern, Growth",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "Hybrid",
    compensation: "$65/hr",
    sponsorship: "Unknown",
    datePosted: hoursAgo(8),
    applicationUrl: "https://www.notion.com/careers",
    category: "SWE",
  },
  {
    id: "scale-ai-2027",
    companyName: "Scale AI",
    roleTitle: "Software Engineering Intern",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "On-Site",
    compensation: "$60/hr",
    sponsorship: "Yes",
    datePosted: hoursAgo(10),
    applicationUrl: "https://scale.com/careers",
    category: "AI/ML",
  },
  {
    id: "goog-swe-2027",
    companyName: "Google",
    roleTitle: "Software Engineering Intern, BS/MS",
    season: "Summer 2027",
    location: "Mountain View, CA",
    workType: "Hybrid",
    compensation: "$11,200/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(12),
    applicationUrl: "https://careers.google.com",
    category: "SWE",
  },
  {
    id: "meta-ai-2027",
    companyName: "Meta",
    roleTitle: "Software Engineer Intern — AI Infra",
    season: "Fall 2026",
    location: "Menlo Park, CA",
    workType: "On-Site",
    compensation: "$10,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(14),
    applicationUrl: "https://www.metacareers.com",
    category: "AI/ML",
  },
  {
    id: "msft-swe-2027",
    companyName: "Microsoft",
    roleTitle: "Software Engineering Intern",
    season: "Summer 2027",
    location: "Redmond, WA",
    workType: "Hybrid",
    compensation: "$7,800/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(16),
    applicationUrl: "https://careers.microsoft.com",
    category: "SWE",
  },
  {
    id: "netflix-swe-2027",
    companyName: "Netflix",
    roleTitle: "Software Engineering Intern, Platform",
    season: "Summer 2027",
    location: "Los Gatos, CA",
    workType: "Hybrid",
    compensation: "$11,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(20),
    applicationUrl: "https://jobs.netflix.com",
    category: "Systems/Infrastructure",
  },
  {
    id: "snowflake-swe-2027",
    companyName: "Snowflake",
    roleTitle: "Software Engineering Intern — Storage",
    season: "Summer 2027",
    location: "San Mateo, CA",
    workType: "Hybrid",
    compensation: "$9,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(22),
    applicationUrl: "https://careers.snowflake.com",
    category: "Systems/Infrastructure",
  },
  {
    id: "databricks-swe-2027",
    companyName: "Databricks",
    roleTitle: "Software Engineering Intern, Lakehouse",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "On-Site",
    compensation: "$13,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(26),
    applicationUrl: "https://databricks.com/company/careers",
    category: "Systems/Infrastructure",
  },
  {
    id: "stripe-swe-2027",
    companyName: "Stripe",
    roleTitle: "Software Engineering Intern",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "Hybrid",
    compensation: "$9,800/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(30),
    applicationUrl: "https://stripe.com/jobs",
    category: "SWE",
  },
  {
    id: "openai-swe-2027",
    companyName: "OpenAI",
    roleTitle: "Software Engineer Intern, Applied",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "On-Site",
    compensation: "$60/hr",
    sponsorship: "Unknown",
    datePosted: hoursAgo(34),
    applicationUrl: "https://openai.com/careers",
    category: "AI/ML",
  },
  {
    id: "anthropic-ai-2027",
    companyName: "Anthropic",
    roleTitle: "Research Engineering Intern — Alignment",
    season: "Winter 2027",
    location: "Remote",
    workType: "Remote",
    compensation: "$70/hr",
    sponsorship: "Yes",
    datePosted: hoursAgo(38),
    applicationUrl: "https://www.anthropic.com/careers",
    category: "AI/ML",
  },
  {
    id: "kanza-bdr-2027",
    companyName: "Kanza Research",
    roleTitle: "Quantitative Developer Intern",
    season: "Summer 2027",
    location: "Boston, MA",
    workType: "On-Site",
    compensation: "$9,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(40),
    applicationUrl: "https://kanzaresearch.com",
    category: "Quant",
  },
  {
    id: "citadel-qr-2027",
    companyName: "Citadel",
    roleTitle: "Quantitative Research Analyst Intern",
    season: "Summer 2027",
    location: "Chicago, IL",
    workType: "On-Site",
    compensation: "$14,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(44),
    applicationUrl: "https://www.citadel.com/careers",
    category: "Quant",
  },
  {
    id: "jump-qr-2027",
    companyName: "Jump Trading",
    roleTitle: "Quant Research Intern",
    season: "Summer 2027",
    location: "Chicago, IL",
    workType: "On-Site",
    compensation: "$15,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(48),
    applicationUrl: "https://www.jumptrading.com/careers",
    category: "Quant",
  },
  {
    id: "hrt-swe-2027",
    companyName: "Hudson River Trading",
    roleTitle: "Software Engineer Intern, Core Systems",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "Hybrid",
    compensation: "$12,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(52),
    applicationUrl: "https://www.hudsonrivertrading.com/careers",
    category: "Quant",
  },
  {
    id: "optiver-swe-2027",
    companyName: "Optiver",
    roleTitle: "SWE Intern, Trading Systems",
    season: "Summer 2027",
    location: "Chicago, IL",
    workType: "On-Site",
    compensation: "$13,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(56),
    applicationUrl: "https://optiver.com/careers",
    category: "Quant",
  },
  {
    id: "square-trading-2027",
    companyName: "Squarepoint Capital",
    roleTitle: "Software Engineer Intern",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "On-Site",
    compensation: "$10,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(60),
    applicationUrl: "https://squarepoint-capital.com",
    category: "Quant",
  },
  {
    id: "robinhood-swe-2027",
    companyName: "Robinhood",
    roleTitle: "Software Engineer Intern, Backend",
    season: "Summer 2027",
    location: "Menlo Park, CA",
    workType: "Hybrid",
    compensation: "$9,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(66),
    applicationUrl: "https://careers.robinhood.com",
    category: "SWE",
  },
  {
    id: "datadog-swe-2027",
    companyName: "Datadog",
    roleTitle: "Software Engineer Intern",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "Hybrid",
    compensation: "$9,200/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(72),
    applicationUrl: "https://careers.datadoghq.com",
    category: "Systems/Infrastructure",
  },
  {
    id: "segway-swe-2027",
    companyName: "Figma",
    roleTitle: "Software Engineer Intern, Web Core",
    season: "Fall 2026",
    location: "San Francisco, CA",
    workType: "Hybrid",
    compensation: "$60/hr",
    sponsorship: "Unknown",
    datePosted: hoursAgo(80),
    applicationUrl: "https://www.figma.com/careers",
    category: "SWE",
  },
  {
    id: "bigbasket-2027",
    companyName: "Vercel",
    roleTitle: "Software Engineer Intern — Edge Platform",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "Hybrid",
    compensation: "$11,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(90),
    applicationUrl: "https://vercel.com/careers",
    category: "Systems/Infrastructure",
  },
  {
    id: "waymo-swe-2027",
    companyName: "Waymo",
    roleTitle: "Software Engineer Intern, Autonomy",
    season: "Summer 2027",
    location: "Mountain View, CA",
    workType: "On-Site",
    compensation: "$10,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(100),
    applicationUrl: "https://waymo.com/careers",
    category: "AI/ML",
  },
  {
    id: "anduril-embedded-2027",
    companyName: "Anduril",
    roleTitle: "Software Engineer Intern — Mission Autonomy",
    season: "Summer 2027",
    location: "Costa Mesa, CA",
    workType: "On-Site",
    compensation: "$9,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(120),
    applicationUrl: "https://www.anduril.com/careers",
    category: "Systems/Infrastructure",
  },
  {
    id: "goldsman-sachs-2027",
    companyName: "Goldman Sachs",
    roleTitle: "Software Engineering Summer Analyst",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "On-Site",
    compensation: "$8,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(140),
    applicationUrl: "https://www.goldmansachs.com/careers",
    category: "Quant",
  },
  {
    id: "stripe-fall-2026",
    companyName: "Stripe",
    roleTitle: "Software Engineering Intern, Payments",
    season: "Fall 2026",
    location: "Dublin, Ireland",
    workType: "On-Site",
    compensation: "Not Listed",
    sponsorship: "No",
    datePosted: hoursAgo(170),
    applicationUrl: "https://stripe.com/jobs",
    category: "SWE",
  },
  {
    id: "uber-swe-2027",
    companyName: "Uber",
    roleTitle: "Software Engineer Intern, Maps",
    season: "Summer 2027",
    location: "Seattle, WA",
    workType: "Hybrid",
    compensation: "$9,800/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(200),
    applicationUrl: "https://www.uber.com/careers",
    category: "SWE",
  },
  {
    id: "roblox-xr-2027",
    companyName: "Roblox",
    roleTitle: "Software Engineer Intern — Avatar Rendering",
    season: "Summer 2027",
    location: "San Mateo, CA",
    workType: "On-Site",
    compensation: "$9,800/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(240),
    applicationUrl: "https://careers.roblox.com",
    category: "Systems/Infrastructure",
  },
  {
    id: "cockroach-infra-2027",
    companyName: "Cockroach Labs",
    roleTitle: "Software Engineer Intern, Distributed SQL",
    season: "Summer 2027",
    location: "Remote",
    workType: "Remote",
    compensation: "$55/hr",
    sponsorship: "Unknown",
    datePosted: hoursAgo(280),
    applicationUrl: "https://www.cockroachlabs.com/careers",
    category: "Systems/Infrastructure",
  },
  {
    id: "akuna-quant-2027",
    companyName: "Akuna Capital",
    roleTitle: "Quantitative Developer Intern",
    season: "Summer 2027",
    location: "Chicago, IL",
    workType: "On-Site",
    compensation: "$10,000/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(320),
    applicationUrl: "https://akunacapital.com/careers",
    category: "Quant",
  },
  {
    id: "cohere-ai-2027",
    companyName: "Cohere",
    roleTitle: "Machine Learning Engineer Intern",
    season: "Fall 2026",
    location: "Remote",
    workType: "Remote",
    compensation: "$7,500/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(360),
    applicationUrl: "https://cohere.com/careers",
    category: "AI/ML",
  },
  {
    id: "imc-quant-2027",
    companyName: "IMC Trading",
    roleTitle: "Quant Trading Intern",
    season: "Summer 2027",
    location: "Chicago, IL",
    workType: "On-Site",
    compensation: "$15,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(400),
    applicationUrl: "https://www.imc.com/us/careers",
    category: "Quant",
  },
  {
    id: "microsoft-hybrid-2026",
    companyName: "Microsoft",
    roleTitle: "Software Engineering Intern, Azure ML",
    season: "Fall 2026",
    location: "Redmond, WA",
    workType: "Hybrid",
    compensation: "Not Listed",
    sponsorship: "Unknown",
    datePosted: hoursAgo(580),
    applicationUrl: "https://careers.microsoft.com",
    category: "AI/ML",
  },
  {
    id: "twitch-embedded-2027",
    companyName: "Twitch",
    roleTitle: "Software Engineering Intern — Video Platform",
    season: "Winter 2027",
    location: "San Francisco, CA",
    workType: "Hybrid",
    compensation: "$9,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(720),
    applicationUrl: "https://www.twitch.tv/jobs",
    category: "Systems/Infrastructure",
  },
  {
    id: "postman-swe-2027",
    companyName: "Postman",
    roleTitle: "Software Engineering Intern",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "Hybrid",
    compensation: "$8,000/mo",
    sponsorship: "No",
    datePosted: hoursAgo(860),
    applicationUrl: "https://www.postman.com/company/careers",
    category: "SWE",
  },
  {
    id: "anthropic-ai-fall-2026",
    companyName: "Anthropic",
    roleTitle: "Software Engineer Intern, Tooling",
    season: "Fall 2026",
    location: "San Francisco, CA",
    workType: "Hybrid",
    compensation: "$9,000/mo",
    sponsorship: "Unknown",
    datePosted: hoursAgo(1000),
    applicationUrl: "https://www.anthropic.com/careers",
    category: "AI/ML",
  },
  {
    id: "pltr-de-2027",
    companyName: "Palantir",
    roleTitle: "Deployment Strategist Intern",
    season: "Summer 2027",
    location: "Washington, DC",
    workType: "Hybrid",
    compensation: "$10,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(1200),
    applicationUrl: "https://www.palantir.com/careers",
    category: "SWE",
  },
  {
    id: "nvidia-ai-2027",
    companyName: "NVIDIA",
    roleTitle: "Deep Learning intern — TensorRT",
    season: "Summer 2027",
    location: "Santa Clara, CA",
    workType: "On-Site",
    compensation: "$65/hr",
    sponsorship: "Yes",
    datePosted: hoursAgo(1400),
    applicationUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    category: "AI/ML",
  },
  {
    id: "squarex-2027",
    companyName: "Cockroach Labs",
    roleTitle: "Site Reliability Engineer Intern",
    season: "Summer 2027",
    location: "Remote",
    workType: "Remote",
    compensation: "Not Listed",
    sponsorship: "Unknown",
    datePosted: hoursAgo(1600),
    applicationUrl: "https://www.cockroachlabs.com/careers",
    category: "Systems/Infrastructure",
  },
  {
    id: "deshaw-quant-2027",
    companyName: "D. E. Shaw",
    roleTitle: "Quantitative Analyst Intern",
    season: "Summer 2027",
    location: "New York, NY",
    workType: "On-Site",
    compensation: "$11,500/mo",
    sponsorship: "Yes",
    datePosted: hoursAgo(1800),
    applicationUrl: "https://www.deshaw.com/careers",
    category: "Quant",
  },
];