import type { Job } from "./types";

const LOGO = (domain: string) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=64`;

export const JOBS: Job[] = [
  {
    id: "scale-ai-software-engineering-intern-summer-2027",
    companyName: "Scale AI",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=scale.com&sz=64",
    roleTitle: "Software Engineering Intern (Summer 2027) ",
    season: "Summer 2027",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T21:37:32-04:00",
    applicationUrl: "https://job-boards.greenhouse.io/scaleai/jobs/4730845005",
    category: "SWE",
  },
  {
    id: "roblox-2027-software-engineer-early-career",
    companyName: "Roblox",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=roblox.com&sz=64",
    roleTitle: "[2027] Software Engineer, Early Career",
    season: "2027",
    location: "San Mateo, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T14:37:13-04:00",
    applicationUrl: "https://careers.roblox.com/jobs/8072244?gh_jid=8072244",
    category: "SWE",
  },
  {
    id: "roblox-summer-2027-software-engineer-intern",
    companyName: "Roblox",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=roblox.com&sz=64",
    roleTitle: "[Summer 2027] Software Engineer Intern",
    season: "Summer 2027",
    location: "San Mateo, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T14:36:02-04:00",
    applicationUrl: "https://careers.roblox.com/jobs/8072713?gh_jid=8072713",
    category: "SWE",
  },
  {
    id: "stripe-software-engineer-intern-summer-or-winter",
    companyName: "Stripe",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=stripe.com&sz=64",
    roleTitle: "Software Engineer, Intern (Summer or Winter)",
    season: "Summer",
    location: "San Francisco, Seattle, New York",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T14:12:15-04:00",
    applicationUrl: "https://stripe.com/jobs/search?gh_jid=8128745",
    category: "SWE",
  },
  {
    id: "stripe-software-engineer-new-grad",
    companyName: "Stripe",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=stripe.com&sz=64",
    roleTitle: "Software Engineer, New Grad",
    season: "Rolling",
    location: "San Francisco, Seattle, NY",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T14:12:15-04:00",
    applicationUrl: "https://stripe.com/jobs/search?gh_jid=8128744",
    category: "SWE",
  },
  {
    id: "scale-ai-software-engineer-new-grad",
    companyName: "Scale AI",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=scale.com&sz=64",
    roleTitle: "Software Engineer - New Grad",
    season: "Rolling",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T12:53:37-04:00",
    applicationUrl: "https://job-boards.greenhouse.io/scaleai/jobs/4730836005",
    category: "SWE",
  },
  {
    id: "amazon-software-development-engineer-intern-robo",
    companyName: "Amazon",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64",
    roleTitle: "Software Development Engineer Intern, ROBOTICS - 2027",
    season: "2027",
    location: "North Reading, MA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-04T04:00:00.000Z",
    applicationUrl: "https://www.amazon.jobs/en/jobs/10529525",
    category: "SWE",
  },
  {
    id: "waymo-2027-summer-intern-ms-software-engineering",
    companyName: "Waymo",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=waymo.com&sz=64",
    roleTitle: "2027 Summer Intern, MS, Software Engineering, Behavior Test ",
    season: "Summer",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-03T20:19:33-04:00",
    applicationUrl: "https://careers.withwaymo.com/jobs?gh_jid=8174504",
    category: "SWE",
  },
  {
    id: "waymo-2027-summer-intern-ms-phd-data-science-com",
    companyName: "Waymo",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=waymo.com&sz=64",
    roleTitle: "2027 Summer Intern, MS/PhD, Data Science - Commercialization Testing",
    season: "Summer",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-03T20:19:14-04:00",
    applicationUrl: "https://careers.withwaymo.com/jobs?gh_jid=8167323",
    category: "SWE",
  },
  {
    id: "datadog-software-engineering-intern-winter",
    companyName: "Datadog",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=datadoghq.com&sz=64",
    roleTitle: "Software Engineering Intern (Winter)",
    season: "Winter",
    location: "Boston, Massachusetts, ; New York, NY",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-09-02T10:22:15-04:00",
    applicationUrl: "https://careers.datadoghq.com/detail/8052095/?gh_jid=8052095",
    category: "SWE",
  },
  {
    id: "amazon-software-development-engineer-intern-anna",
    companyName: "Amazon",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64",
    roleTitle: "Software Development Engineer Intern, Annapurna Labs - 2027",
    season: "2027",
    location: "Cupertino, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-27T04:00:00.000Z",
    applicationUrl: "https://www.amazon.jobs/en/jobs/10517567",
    category: "SWE",
  },
  {
    id: "amazon-asic-engineer-intern-annapurna-labs-2027",
    companyName: "Amazon",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64",
    roleTitle: "ASIC Engineer Intern, Annapurna Labs - 2027",
    season: "2027",
    location: "Cupertino, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-27T04:00:00.000Z",
    applicationUrl: "https://www.amazon.jobs/en/jobs/10517535",
    category: "SWE",
  },
  {
    id: "amazon-robotics-software-development-engineer-fa",
    companyName: "Amazon",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64",
    roleTitle: "Robotics - Software Development Engineer Fall Intern/Co-op - 2026",
    season: "Fall",
    location: "Westboro, MA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-27T04:00:00.000Z",
    applicationUrl: "https://www.amazon.jobs/en/jobs/10517149",
    category: "SWE",
  },
  {
    id: "figma-software-engineer-intern-winter-2027",
    companyName: "Figma",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=figma.com&sz=64",
    roleTitle: "Software Engineer Intern (Winter 2027)",
    season: "Winter 2027",
    location: "San Francisco, CA • New York, NY",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-24T18:00:23-04:00",
    applicationUrl: "https://boards.greenhouse.io/figma/jobs/6131089004?gh_jid=6131089004",
    category: "SWE",
  },
  {
    id: "databricks-software-engineering-intern-2027-star",
    companyName: "Databricks",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=databricks.com&sz=64",
    roleTitle: "Software Engineering Intern (2027 Start) - Winter",
    season: "Winter",
    location: "Bellevue, Washington; Mountain View, California; San Fran...",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-21T16:45:24-04:00",
    applicationUrl: "https://databricks.com/company/careers/open-positions/job?gh_jid=8732364002",
    category: "SWE",
  },
  {
    id: "databricks-phd-genai-research-scientist-intern",
    companyName: "Databricks",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=databricks.com&sz=64",
    roleTitle: "PhD GenAI Research Scientist Intern",
    season: "Rolling",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-18T13:17:06-04:00",
    applicationUrl: "https://databricks.com/company/careers/open-positions/job?gh_jid=7011263002",
    category: "SWE",
  },
  {
    id: "postman-ai-engineer-internship-summer-2026-appli",
    companyName: "Postman",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=postman.com&sz=64",
    roleTitle: "AI Engineer, Internship - Summer 2026 - Applications Open Now",
    season: "Summer 2026",
    location: "Berkeley, California, United States; San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-17T18:15:55-04:00",
    applicationUrl: "https://job-boards.greenhouse.io/postman/jobs/7823417003",
    category: "SWE",
  },
  {
    id: "nvidia-applied-deep-learning-phd-research-intern",
    companyName: "NVIDIA",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=64",
    roleTitle: "Applied Deep Learning PhD Research Intern, Reinforcement Learning for LLMs - Fall 2026",
    season: "Fall 2026",
    location: "US, CA, Santa Clara",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-06T02:51:06.409Z",
    applicationUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/Applied-Deep-Learning-PhD-Research-Intern--Reinforcement-Learning-for-LLMs---Fall-2026_JR2012398",
    category: "AI/ML",
  },
  {
    id: "nvidia-phd-software-engineering-intern-decision-",
    companyName: "NVIDIA",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=64",
    roleTitle: "PhD Software Engineering Intern, Decision Intelligence - Fall 2026",
    season: "Fall 2026",
    location: "US, CA, Santa Clara",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-06T02:51:06.409Z",
    applicationUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/PhD-Software-Engineering-Intern--Decision-Intelligence---Fall-2026_JR2017522",
    category: "SWE",
  },
  {
    id: "nvidia-phd-research-intern-generative-ai-2026",
    companyName: "NVIDIA",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=64",
    roleTitle: "PhD Research Intern, Generative AI - 2026",
    season: "2026",
    location: "US, CA, Santa Clara",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-06T02:51:06.409Z",
    applicationUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/PhD-Research-Intern--Generative-AI---2026_JR2016035",
    category: "SWE",
  },
  {
    id: "nvidia-applied-research-intern-nlp-fall-2026",
    companyName: "NVIDIA",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=64",
    roleTitle: "Applied Research Intern, NLP - Fall 2026",
    season: "Fall 2026",
    location: "US, CA, Santa Clara",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2026-08-06T02:51:06.409Z",
    applicationUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/Applied-Research-Intern--NLP---Fall-2026_JR2010488",
    category: "SWE",
  },
  {
    id: "palantir-forward-deployed-infrastructure-enginee",
    companyName: "Palantir",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=palantir.com&sz=64",
    roleTitle: "Forward Deployed Infrastructure Engineer, New Grad - US Government",
    season: "Rolling",
    location: "Palo Alto, CA",
    workType: "Hybrid",
    sponsorship: "Unknown",
    datePosted: "2025-10-29T20:26:17.197Z",
    applicationUrl: "https://jobs.lever.co/palantir/33243fb5-6907-40c7-930c-968b25d825d0",
    category: "Systems/Infrastructure",
  },
  {
    id: "palantir-1",
    companyName: "Palantir",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=palantir.com&sz=64",
    roleTitle: "Forward Deployed Software Engineer, Internship - Defense Tech",
    season: "Rolling",
    location: "Washington, D.C.",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2024-08-05T23:14:32.789Z",
    applicationUrl: "https://jobs.lever.co/palantir/cccfe1bd-f15b-4fe5-b044-c793e7961c1b",
    category: "SWE",
  },
  {
    id: "palantir-forward-deployed-software-engineer-inte",
    companyName: "Palantir",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=palantir.com&sz=64",
    roleTitle: "Forward Deployed Software Engineer, Internship - Commercial",
    season: "Rolling",
    location: "New York, NY",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "2016-02-24T23:37:05.251Z",
    applicationUrl: "https://jobs.lever.co/palantir/4d29249a-d7e8-4c39-880d-3b35d7b2f6f6",
    category: "SWE",
  },
  {
    id: "snowflake-ai-research-scientist-new-grad-agents-",
    companyName: "Snowflake",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=snowflake.com&sz=64",
    roleTitle: "AI Research Scientist, New Grad – Agents & Reinforcement Learning",
    season: "Rolling",
    location: "US-WA-Bellevue",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "1970-01-01T00:00:00.000Z",
    applicationUrl: "https://jobs.ashbyhq.com/snowflake/1bad12df-f443-426f-9d09-e96fc780d698",
    category: "SWE",
  },
  {
    id: "notion-software-engineer-early-career-ai",
    companyName: "Notion",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
    roleTitle: "Software Engineer, Early Career (AI)",
    season: "Rolling",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "1970-01-01T00:00:00.000Z",
    applicationUrl: "https://jobs.ashbyhq.com/notion/85947779-6b87-466a-98bc-30a640448c28",
    category: "SWE",
  },
  {
    id: "notion-software-engineer-early-career",
    companyName: "Notion",
    companyLogoUrl: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
    roleTitle: "Software Engineer, Early Career",
    season: "Rolling",
    location: "San Francisco, CA",
    workType: "On-Site",
    sponsorship: "Unknown",
    datePosted: "1970-01-01T00:00:00.000Z",
    applicationUrl: "https://jobs.ashbyhq.com/notion/297b4ece-765f-4eea-b1b8-46057cb6501f",
    category: "SWE",
  },
];
